# Generated by Django 2.0.2 on 2018-02-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='text',
        ),
    ]
